### ISSUE TITLE
Error while using the function Create

### ISSUE THREAD

**Issue by viktor-morin** [a8m/documentdb#14]
While creating a document you get an error that  `x-ms-documentdb-partitionkey` is missing in the header.
By adding following:

`	if id != "" {
		r.Header.Add("x-ms-documentdb-partitionkey", fmt.Sprintf("[ \"%s\" ]", id))
	}`

The problem get solved. I have just extended the method (just fixed it locally), but I assume its better to read the property Id if needed from the object itself.

**Comment by ItalyPaleAle** [comment]
I have the same issue @a8m.

@viktor-morin mind sharing how you fixed this?

**Comment by ItalyPaleAle** [comment]
To add some context: Partition Keys are now mandatory: https://github.com/MicrosoftDocs/azure-docs/issues/20882 I can't figure out how to add the partition key header in the library, however (and the partition key should not be the ID of the document)

**Comment by viktor-morin** [comment]
@ItalyPaleAle 

If I remeber correctly I added that line here:
https://github.com/a8m/documentdb/blob/f1cda923df27a4b5551f6776cb9f5fd7134713ed/client.go#L127

**Comment by ItalyPaleAle** [comment]
@viktor-morin thanks for responding. I figured out just a couple of minutes ago that the code is available today, but only in the "master" branch. So, when running a normal "go get", it will fetch the v1.0.0 tag which doesn't support adding headers like these.

The method that works for me, after pulling the code with @master, is:

````go
func (u *DocumentDB) Add(document *Document) (err error) {
	pk := documentdb.PartitionKey(document.User)
	_, err = conn.CreateDocument(u.coll.Self, document, pk)
	return
}
````

**Comment by a8m** [comment]
Hey guys,
Sorry for the troubles. I've added a new release tag (v.1.1.0).

Would you mind update the README? 
Thanks
